### PR TITLE
Improve the project

### PR DESCRIPTION
**Pull request by janaSunrise**
Changes done:
- Added `to_async` function to convert blocking func to async.
- Convert API to a module.
- Added Async SQLITE module.
- Clean and lint things.
- Switch to pipenv.

### CODE REVIEW

**Comment by GrandMoff100** [comment]
Does Sid like to use pipenv?

**Comment by Overthrowing** [comment]
I haven't really used it in the past but it's actually pretty nice.

**Comment by GrandMoff100** [comment]
Sweet!

**Comment by janaSunrise** [comment]
It's actually amazing! 🔥 
Also, Changing to Async for everything is required, Even added a quick decorator `to_async` to simplify it 😉

**Comment by GrandMoff100** [comment]
Nice

**Pull request merged**
